"""empty message

Revision ID: 6957d2c6b719
Revises: df91bb2c4076
Create Date: 2023-12-13 19:40:20.755211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6957d2c6b719'
down_revision = 'df91bb2c4076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=250), nullable=False))
        batch_op.drop_constraint('character_email_key', type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('character_email_key', ['email'])
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
